### ISSUE TITLE
su dung jekyllrb cho iojs-vi.com

### ISSUE THREAD

**Issue by particle4dev** [iojs/iojs-vi#17]
Trong khi mọi người đều bận fulltime, jekyllrb là giải pháp tốt nhất hiện nay. @thanhlvbk @nhatquang238

**Comment by particle4dev** [comment]
https://github.com/jekyll/jekyll
http://jekyllthemes.org/

**Comment by thanhlvbk** [comment]
Đồng ý!. Có vẻ như jekyllrb là giải pháp tốt nhất cho hiện tại
