### ISSUE TITLE
Connect with Vietnam-based NodeSchool chapters

### ISSUE THREAD

**Issue by dominhhai** [iojs/iojs-vi#21]
Hi there, 
I'm Hai - an org-er of [NodeSchool Hanoi](https://github.com/nodeschool/hanoi)

I have an idea that cooperate all Vietnam's nodejs, iojs communities such as [NodeSchool Hanoi](https://github.com/nodeschool/hanoi), [NodeSchool Ho Chi Minh](https://github.com/nodeschool/hcmc-vietnam) and [nodejs.vn](http://nodejs.vn/).

The main reason to do that is: 
1. Easily to communicate, share, support others
2. One place for all activities as meet-up, learn or hire...
3. Easily to cooperate in opensource projects

Now, I don't have a specific plan. So, it's nice if we can do that with great effort.

Best,
Hai

**Comment by particle4dev** [comment]
Hi Hai,
This is great ideal ! I am busy with my full time job so i don't usually have time to write or post blog. 
Do you have any skype account or google hangout so we chat about it ? My skype account is `particle4dev` and my email is `particle4dev@gmail.com`.

Cheers,
Le Hoang

**Comment by dominhhai** [comment]
Thank you very much!
I sent friend request to you via Skype with `dominhhai255` account. Please accept :100:
